export const mockRaces = [
  {
    city: 'Bahrain',
    slug: 'bahrain',
    title: 'Bahrain F1',
    date: '2025-04-13',
    month: 'April',
    continent: 'Asien',
    circuit: 'Bahrain International Circuit',
    priceTicketOnly: 4595,
    priceTicketHotel: 6330,
    priceFullPackage: 21625,
  },
  {
    city: 'Jeddah',
    slug: 'jeddah',
    title: 'Saudi Arabia F1 - Jeddah',
    date: '2025-04-20',
    month: 'April',
    continent: 'Asien',
    circuit: 'Jeddah Street Circuit',
    priceTicketOnly: 1865,
    priceTicketHotel: 3110,
    priceFullPackage: 13665,
  },
  {
    city: 'Miami',
    slug: 'miami',
    title: 'USA F1 - Miami',
    date: '2025-05-04',
    month: 'Maj',
    continent: 'Nordamerika',
    circuit: 'Miami International Autodrome',
    priceTicketOnly: 5985,
    priceTicketHotel: 7770,
    priceFullPackage: 13165,
  },
  {
    city: 'Imola',
    slug: 'imola',
    title: 'Italy F1 - Imola',
    date: '2025-05-18',
    month: 'Maj',
    continent: 'Europa',
    circuit: 'Autodromo Enzo E Dino Ferrari',
    priceTicketOnly: 1815,
    priceTicketHotel: 2720,
    priceFullPackage: 8105,
  },
  {
    city: 'Monte Carlo',
    slug: 'monte-carlo',
    title: 'Monaco F1 - Monte Carlo',
    date: '2025-05-25',
    month: 'Maj',
    continent: 'Europa',
    circuit: 'Circuit De Monaco',
    priceTicketOnly: 10585,
    priceTicketHotel: 11750,
    priceFullPackage: 14905,
  },
  {
    city: 'Barcelona',
    slug: 'barcelona',
    title: 'Spain F1 - Barcelona',
    date: '2025-06-01',
    month: 'Juni',
    continent: 'Europa',
    circuit: 'Circuit De Catalunya',
    priceTicketOnly: 2395,
    priceTicketHotel: 3360,
    priceFullPackage: 7055,
  },
]
