export const mockRaces = [
  {
    city: 'Bahrain',
    slug: 'bahrain',
    title: 'Bahrain Grand Prix',
    date: '2025-04-13',
    month: 'April',
    continent: 'Asien',
    circuit: 'Bahrain International Circuit',
    priceTicketOnly: 4595,
    priceTicketHotel: 6330,
    priceFullPackage: 21625,
    price: 4595,
    image: '/images/races/default.jpg',
    offers: [
      {
        id: 'bahrain-1',
        provider: 'F1Resor.se',
        price: 4595,
        url: 'https://f1resor.se/bahrain/biljett',
        description: 'Endast F1-biljett till läktare sektion A',
      },
      {
        id: 'bahrain-2',
        provider: 'GoSportTravel',
        price: 6330,
        url: 'https://gosporttravel.com/bahrain/hotellpaket',
        description: 'F1-biljett + 2 nätter på hotell i Manama',
      },
      {
        id: 'bahrain-3',
        provider: 'F1Experience',
        price: 21625,
        url: 'https://f1experience.com/bahrain/komplett',
        description: 'Biljett + hotell + flyg från Stockholm',
      },
    ],
  },
  {
    city: 'Jeddah',
    slug: 'jeddah',
    title: 'Saudiarabien Grand Prix – Jeddah',
    date: '2025-04-20',
    month: 'April',
    continent: 'Asien',
    circuit: 'Jeddah Street Circuit',
    priceTicketOnly: 1865,
    priceTicketHotel: 3110,
    priceFullPackage: 13665,
    price: 1865,
    image: '/images/races/default.jpg',
    offers: [
      {
        id: 'jeddah-1',
        provider: 'F1Resor.se',
        price: 1865,
        url: 'https://f1resor.se/jeddah/biljett',
        description: 'Endast biljett – huvudläktare',
      },
      {
        id: 'jeddah-2',
        provider: 'Resfeber',
        price: 3110,
        url: 'https://resfeber.se/jeddah/hotellpaket',
        description: '2 nätter + F1-biljett',
      },
      {
        id: 'jeddah-3',
        provider: 'F1TravelNow',
        price: 13665,
        url: 'https://f1travelnow.com/jeddah/full',
        description: 'Paket med hotell & flyg från Göteborg',
      },
    ],
  },
  {
    city: 'Miami',
    slug: 'miami',
    title: 'USA Grand Prix – Miami',
    date: '2025-05-04',
    month: 'Maj',
    continent: 'Nordamerika',
    circuit: 'Miami International Autodrome',
    priceTicketOnly: 5985,
    priceTicketHotel: 7770,
    priceFullPackage: 13165,
    price: 5985,
    image: '/images/races/default.jpg',
    offers: [
      {
        id: 'miami-1',
        provider: 'USAresor.nu',
        price: 5985,
        url: 'https://usaresor.nu/miami/f1-biljett',
        description: 'Biljett till F1 Miami – Standardsektion',
      },
      {
        id: 'miami-2',
        provider: 'GoSportTravel',
        price: 7770,
        url: 'https://gosporttravel.com/miami/hotellpaket',
        description: 'Biljett + 2 nätter på centralt hotell',
      },
      {
        id: 'miami-3',
        provider: 'F1Experience',
        price: 13165,
        url: 'https://f1experience.com/miami/full-package',
        description: 'VIP-biljett + hotell & direktflyg',
      },
    ],
  },
  {
    city: 'Imola',
    slug: 'imola',
    title: 'Italien Grand Prix – Imola',
    date: '2025-05-18',
    month: 'Maj',
    continent: 'Europa',
    circuit: 'Autodromo Enzo e Dino Ferrari',
    priceTicketOnly: 1815,
    priceTicketHotel: 2720,
    priceFullPackage: 8105,
    price: 1815,
    image: '/images/races/default.jpg',
    offers: [
      {
        id: 'imola-1',
        provider: 'F1Italia',
        price: 1815,
        url: 'https://f1italia.it/imola/biljett',
        description: 'Endast biljett till huvudrakan',
      },
      {
        id: 'imola-2',
        provider: 'SportEventTravel',
        price: 2720,
        url: 'https://sporteventtravel.se/imola/hotel',
        description: '2 nätter + biljett',
      },
      {
        id: 'imola-3',
        provider: 'F1Resor.se',
        price: 8105,
        url: 'https://f1resor.se/imola/paket',
        description: 'Hotell & flygpaket + premiumbiljett',
      },
    ],
  },
  {
    city: 'Monte Carlo',
    slug: 'monte-carlo',
    title: 'Monaco Grand Prix – Monte Carlo',
    date: '2025-05-25',
    month: 'Maj',
    continent: 'Europa',
    circuit: 'Circuit de Monaco',
    priceTicketOnly: 10585,
    priceTicketHotel: 11750,
    priceFullPackage: 14905,
    price: 10585,
    image: '/images/races/default.jpg',
    offers: [
      {
        id: 'monaco-1',
        provider: 'F1Exclusive',
        price: 10585,
        url: 'https://f1exclusive.com/monaco/biljett',
        description: 'Endast biljett till Casino Square',
      },
      {
        id: 'monaco-2',
        provider: 'GoSportTravel',
        price: 11750,
        url: 'https://gosporttravel.com/monaco/hotell',
        description: 'Lyxhotell + biljett på huvudläktare',
      },
      {
        id: 'monaco-3',
        provider: 'F1TravelNow',
        price: 14905,
        url: 'https://f1travelnow.com/monaco/full',
        description: 'VIP-paket med hotell & flyg',
      },
    ],
  },
  {
    city: 'Barcelona',
    slug: 'barcelona',
    title: 'Spanien Grand Prix – Barcelona',
    date: '2025-06-01',
    month: 'Juni',
    continent: 'Europa',
    circuit: 'Circuit de Catalunya',
    priceTicketOnly: 2395,
    priceTicketHotel: 3360,
    priceFullPackage: 7055,
    price: 2395,
    image: '/images/races/default.jpg',
    offers: [
      {
        id: 'barcelona-1',
        provider: 'F1Resor.se',
        price: 2395,
        url: 'https://f1resor.se/barcelona/biljett',
        description: 'Standardbiljett till läktare C',
      },
      {
        id: 'barcelona-2',
        provider: 'Resfeber',
        price: 3360,
        url: 'https://resfeber.se/barcelona/hotell',
        description: '2 nätter på hotell + biljett',
      },
      {
        id: 'barcelona-3',
        provider: 'F1TravelNow',
        price: 7055,
        url: 'https://f1travelnow.com/barcelona/full',
        description: 'Paketresa med hotell & flyg',
      },
    ],
  },
]
